#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: PLTW POE Programming
  Team Members: Brandon Takahashi, Ryan Frey, Jaiden Cochenour
  Date: 5/2/16
  Section: 3.1.1


  Task Description:


  Pseudocode:

*/

task main()
{                                     //Program begins, insert code within curly braces
	turnLEDOff(green);     							//initializes green LED light in the program, starting in the off position
	wait(1);														//runs previous code for 1 second before moving on
	turnLEDOn(green);										//Turns on the green LED
	wait(1);														//runs previous code for 1 second before moving on
	turnLEDOff(green);									//Turns off the Green LED
	wait(1);														//runs previous code for 1 second before moving on
	turnLEDOn(green);										//Turns on the green LED
	wait(1);														//runs previous code for 1 second before moving on
	turnLEDOff(green);									//Turns off the Green LED


}
