#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: PLTW POE Programming
  Team Members: Brandon Takahashi, Ryan Frey, Jaiden Cochenour
  Date: 5/2/16
  Section: 3.1.1


  Task Description:


  Pseudocode:

*/

task main()
{                                     //Program begins, insert code within curly braces
	untilBump(bumpSwitch);							//Waits for the bump switch to be activated to initiate the code below
	startMotor(rightMotor , (127/2));		//Starts the right motor after the bump switch has been triggered
	startMotor(leftMotor , (127/2));		//Starts the left motor after the bump switch has been triggered
	untilBump(bumpSwitch);							//Once the bump switch has been triggered a second time, it will move on to the code below
	startMotor(rightMotor , (-127/2));	//Starts the right motor in reverse after the bump switch was triggered
	startMotor(leftMotor , (-127/2));		//Starts the left motor in reverse after the bump switch was triggered
	wait(3.5);													//Runs the above code for 3.5 seconds
	stopMotor(leftMotor);								//Stops the left motor
	stopMotor(rightMotor);							//Stops the right motor
}
