#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title: PLTW POE Programming
Team Members: Brandon Takahashi, Ryan Frey, Jaiden Cochenour
Date: 5/2/16
Section: 3.1.1


Task Description:
To learn how to use the potentiometer

Pseudocode:
We want to turn on the green led, then turn it off when we spin the potentiometer
to a value greater then 2048. When this happens, we want to turn off the led and
power a motor until the potentiometer is once again moved, this time to a value below 2048.

*/

task main()
{                                     									//Program begins, insert code within curly braces
	turnLEDOn(green);																			//Turns the led on
	untilPotentiometerGreaterThan(2048, potentiometer);		//Waits for the potentiometer to reach a value above 2048 before the program moves on
	turnLEDOff(green);																		//Turns the led off
	startMotor(leftMotor, 63);														//Starts the motor
	untilPotentiometerLessThan(2048, potentiometer);      //Runs the above code until the potentiometer reaches a value less than 2048, where it then moves on
	stopMotor(leftMotor);																	//Stops the motor
}
