#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title: PLTW POE Programming
Team Members: Brandon Takahashi, Ryan Frey, Jaiden Cochenour
Date: 5/2/16
Section: 3.1.1


Task Description:
Learning how to use the while loop and if statement together

Pseudocode:
While the limit switch is pressed, and the light sensor detects a dark area, the flashlight will turn on
if there is no dark room detected, the flashlight will turn off
*/

task main(){                                    //Program begins, insert code within curly braces
	while(true){																	//Infinite loop
		while(SensorValue(limitSwitch) == 1){				//detects if the limit switch is pressed
			if(SensorValue(lightSensor) > 500){				//looks if the room is dark
				turnFlashlightOn(flashlight , 127);			//turns flashlight
			}
			else{																			//if the room is not dark, moves to next code
				turnFlashlightOff(flashlight);					//turns off the flashlight
			}
		}
	}
}
